project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Popular Baby Name in NYC"
  author:
    - Fenghang Yao (fy2308)
    - Linxuan Zheng (lz2656)
  repo-url: https://github.com/dorisyao06/PopularBabyNameNYC
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: Sketchy
    code-fold: true


